server:
  port: 8080
  error:
    include-message: ALWAYS

spring:
  application:
    name: Spring-app
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/my-learning
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true